### ISSUE TITLE
Modify CMake to build IQS as static/dynamic lib only

### ISSUE THREAD

**Issue by fbaru-dev** [intel/intel-qs#2]
This is an issue

**Comment by giangiac** [comment]
In CMakeLists.txt there are special options "BuildExamples" and "BuildInterface" that, once set to OFF, exclude the examples, respectively the interface, from compilation. By default they are set on ON and OFF respectively.

A cleaner option is creating different configurations (something like "full", "library", "debug") and call it with something like "cmake --full .."

**Comment by fbaru-dev** [comment]
I like this idea. I have created a new branch to develop a similar solution

**Comment by giangiac** [comment]
Check if the CMake process uses features from version 3.15.
If not, lower the dependency to 3.11

**Comment by fbaru-dev** [comment]
This has been implemented
