### ISSUE TITLE
Building "examples" when the rest of the code is already compiled 

### ISSUE THREAD

**Issue by luigi-iap** [intel/intel-qs#26]
I have tried to build the files in the "examples" directory, while the code was already compiled. Here the list of my commands:
mkdir build
cd build
cmake ..
make
but compiling fails.
A working alternative is to build the whole source from scratch and using the -DBuildExamples=ON flag. I am wondering if this can be avoided by a suitable configuration in the "examples" directory.

**Comment by giangiac** [comment]
Hi @luigi-iap , you have to add the option -DBuild Examples=ON to the cmake command.

For example, consider that you  initially compiled with:
$ mkdirbuild; cd build
$ cmake -DIqsPython=OFF ..
$ make

To add the examples, from the $REPO/build/ folder just run:
$ cmake -DBuildExamples=ON ..
$ make

I just tested it with the master branch and it worked.
Executable files are generated in $REPO/examples/bin/ folder.

Gian

**Comment by luigi-iap** [comment]
Hi Gian, 

thanks for your comment! Yes, compiling the code in the first place with  -DBuildExamples=ON is the right thing to do. In this way, if a single file in the examples folder is edited, the make command will compile it and it only. On a related topic, I discussed with @fbaru-dev to document how to add a new file in the example directory (or in a arbitrary location) and have it properly complied, as it can be beneficial for new users. This can be followed up separately, so that this issue can be closed, if you want. 
Cheers,

  Luigi

**Comment by giangiac** [comment]
Good suggestion!

I created two entries to the Q&A wiki:
https://github.com/iqusoft/intel-qs/wiki/Q&A
One about compiling the examples, and one about adding a new example.

I will close the issue.
