### ISSUE TITLE
SingleQubitGatesTest.CustomGate unit test failed

### ISSUE THREAD

**Issue by wh5a** [intel/intel-qs#33]
**Describe the bug**
/root/intel-qs/unit_test/include/single_qubit_gates_test.hpp:116: Failure
Expected equality of these values:
  psi.GetProbability(0)
    Which is: 0.56170165848894527
  psi.GetProbability(2)
    Which is: 0.56170165848894749
[  FAILED  ] SingleQubitGatesTest.CustomGate (1 ms)

**To Reproduce**
1. Build
2. Run utest

**Expected behavior**
All tests pass.

**Comment by wh5a** [comment]
This only happens with -DIqsNative=ON

**Comment by giangiac** [comment]
@cangumeli Can you look into this?
Thanks!

**Comment by jwhogabo** [comment]
Hi @wh5a,

I'm trying to reproduce this test failure.  The following build configuration passes all tests:
CXX=g++ cmake -DIqsNative=ON -DIqsUtest=ON -DIqsMPI=OFF ..

The following configurations end in a **segmentation fault**:
CXX=icc  cmake -DIqsNative=ON -DIqsUtest=ON -DIqsMPI=OFF ..
bash> bin/utest

CXX=icpc cmake -DIqsNative=ON -DIqsUtest=ON -DIqsMPI=OFF ..
bash> bin/utest

CXX=mpiicpc cmake -DIqsNative=ON -DIqsMPI=ON -DIqsUtest=ON ..
bash> bin/utest

CXX=mpiicpc cmake -DIqsNative=ON -DIqsMPI=ON -DIqsUtest=ON ..
bash> mpirun -n8 -ppn 2 bin/utest

I am unable to reproduce your specific result.  Could you post the CMAKE command line you used to generate your build?  Also, could you let me know your OS version and compiler version as well?

Thanks!

Justin -=-

**Comment by wh5a** [comment]
@jwhogabo Thanks for getting back to me. I installed Intel Parallel Studio 2020 on Ubuntu 18.04. This is my CMAKE command:
CXX=mpiicpc cmake -DIqsMPI=ON -DIqsUtest=ON -DIqsNative=ON ..

ICC version is 19.1.2.254 20200623.

And here's /proc/cpuinfo for one core, with a total of 8 cores:

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel Core Processor (Haswell, no TSX)
stepping	: 1
microcode	: 0x1
cpu MHz		: 3092.734
cache size	: 16384 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single pti fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips	: 6185.46
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

Could this be a processor bug?
