### ISSUE TITLE
Segmentation fault when running Google Tests with various build configurations.

### ISSUE THREAD

**Issue by jwhogabo** [intel/intel-qs#34]
When using the following build generator configurations for IQS on Ubuntu 20.04 LTS, the Google Tests are generating a segmentation fault right before program termination.  Host system is an 8 socket, 28 core / socket, 2 threads per core, Xeon Platinum 8280L w/ 12 TB Optane accessible RAM.

The following configurations end in a segmentation fault:
CXX=icc cmake -DIqsNative=ON -DIqsUtest=ON -DIqsMPI=OFF ..
bash> bin/utest

CXX=icpc cmake -DIqsNative=ON -DIqsUtest=ON -DIqsMPI=OFF ..
bash> bin/utest

CXX=mpiicpc cmake -DIqsNative=ON -DIqsMPI=ON -DIqsUtest=ON ..
bash> bin/utest

CXX=mpiicpc cmake -DIqsNative=ON -DIqsMPI=ON -DIqsUtest=ON ..
bash> mpirun -n8 -ppn 2 bin/utest

**Comment by giangiac** [comment]
@cangumeli This seems to be related to IqsNative option. Can you look into it?
