### ISSUE TITLE
Not able to compile on mac OS Mojave

### ISSUE THREAD

**Issue by shreyasdhole** [intel/intel-qs#36]
Even though g++ is installed and updated, cmake cannot recognise it as a legitimate gnu compiler and I am getting the error message saying that my compiler environment is unsupported

**Comment by giangiac** [comment]
Hi @shreyasdhole ,

I have never compiled it on mac OS, but I have a few colleagues and collaborators who successfully did.
I will ask them to help you with the issue, if you were not able to solve it by now.

Sorry for the late reply!

Gian

**Comment by mofeing** [comment]
@shreyasdhole Have you tried with flags `-DCMAKE_CXX_COMPILER=<PATH_TO_G++> -DCMAKE_C_COMPILER=<PATH_TO_GCC>`?

I'm compiling it correctly in macOS Catalina.

**Comment by giangiac** [comment]
I assume that the compilation issue has been solved and will close the issue.
