### ISSUE TITLE
errors from make all (qHipSTER)

### ISSUE THREAD

**Issue by charliegray** [intel/Intel-QS#4]
**not a c++ programmer.  attempting to build qHiPSTER for a colleague.  have downloaded/sourced the appropriate environment but errors during make all.**

**compiler version as follows:**
[root@omega025 Intel-QS-master]# icpc -V
Intel(R) C++ Intel(R) 64 Compiler XE for applications running on Intel(R) 64, Version 14.0.4.211 Build 20140805
Copyright (C) 1985-2014 Intel Corporation.  All rights reserved.

**edited make.inc and change -qopenmp flag to -openmp to suppress various undefined reference errors.**
icpc: command line warning #10006: ignoring unknown option '-qopenmp'

**here are the results of the make any missing pre-reqs?  any suggestions?**
[root@omega025 Intel-QS-master]# make all
cd util; make
make[1]: Entering directory `/opt/shared/qHiPSTER/src/Intel-QS-master/util'
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64  -Wall -std=c++11 -openmp   -I./ -I../ -c mpi_wrapper.cpp -o mpi_wrapper.o
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64  -Wall -std=c++11 -openmp   -I./ -I../ -c mpi_exception.cpp -o mpi_exception.o
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64  -Wall -std=c++11 -openmp   -I./ -I../ -c mpi.cpp -o mpi.o
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64  -Wall -std=c++11 -openmp   -I./ -I../ -c utils.cpp -o utils.o
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64  -Wall -std=c++11 -openmp   -I./ -I../ -c openmp_affinity_noomp.cpp -o openmp_affinity_noomp.o
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64  -Wall -std=c++11 -openmp   -I./ -I../ -c openmp_affinity_corei7.cpp -o openmp_affinity_corei7.o
make[1]: Leaving directory `/opt/shared/qHiPSTER/src/Intel-QS-master/util'
cd util/tests; make
make[1]: Entering directory `/opt/shared/qHiPSTER/src/Intel-QS-master/util/tests'
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64  -Wall -std=c++11 -openmp   -I./ -I../ -c mpi_exception_test.cpp -o mpi_exception_test.o
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64  -Wall -std=c++11 -openmp   -L/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64 -lmkl_cdft_core -lmkl_intel_ilp64 -lmkl_core -lmkl_intel_thread -lmkl_blacs_intelmpi_ilp64 -lpthread -lirc mpi_exception_test.o ../mpi_exception.o ../mpi_wrapper.o -o mpi_exception_test.exe
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64  -Wall -std=c++11 -openmp   -I./ -I../ -c mpi_test1.cpp -o mpi_test1.o
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64  -Wall -std=c++11 -openmp   -L/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64 -lmkl_cdft_core -lmkl_intel_ilp64 -lmkl_core -lmkl_intel_thread -lmkl_blacs_intelmpi_ilp64 -lpthread -lirc mpi_test1.o ../mpi_wrapper.o ../mpi_exception.o -o mpi_test1.exe
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64  -Wall -std=c++11 -openmp   -I./ -I../ -c omp_test1.cpp -o omp_test1.o
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64  -Wall -std=c++11 -openmp   -L/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64 -lmkl_cdft_core -lmkl_intel_ilp64 -lmkl_core -lmkl_intel_thread -lmkl_blacs_intelmpi_ilp64 -lpthread -lirc omp_test1.o ../openmp_affinity_corei7.o ../openmp_affinity_noomp.o -o omp_test1.exe
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64  -Wall -std=c++11 -openmp   -I./ -I../ -c naive_integral_base.cpp -o naive_integral_base.o
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64  -Wall -std=c++11 -openmp   -L/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64 -lmkl_cdft_core -lmkl_intel_ilp64 -lmkl_core -lmkl_intel_thread -lmkl_blacs_intelmpi_ilp64 -lpthread -lirc naive_integral_base.o -o naive_integral_base.exe
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64  -Wall -std=c++11 -openmp   -I./ -I../ -c omp_integral_base.cpp -o omp_integral_base.o
omp_integral_base.cpp(59): error: name followed by "::" must be a class or namespace name
      auto start = std::chrono::steady_clock::now();
                                ^

omp_integral_base.cpp(80): error: name followed by "::" must be a class or namespace name
      auto end = std::chrono::steady_clock::now();
                              ^

omp_integral_base.cpp(86): error: no instance of function template "std::chrono::duration_cast" matches the argument list
            argument types are: (<error-type>)
                 std::chrono::duration_cast<std::chrono::milliseconds>(diff).count());
                 ^

compilation aborted for omp_integral_base.cpp (code 2)
make[1]: *** [omp_integral_base.o] Error 2
make[1]: Leaving directory `/opt/shared/qHiPSTER/src/Intel-QS-master/util/tests'
make: *** [all] Error 2

**Comment by giangiac** [comment]
The flag -qopenmp enables the parallelizer to generate multi-threaded code based on OpenMP directives. Option -qopenmp is the replacement option for -openmp, which is deprecated [from icpc version 17.0].

The errors refer to a "std::chrono::steady_clock" method, perhaps due to the problem of locating and including the necessary header file (supposedly included via: #include <chrono>).

The errors are from compiling a file to test the implementation of the OpenMP wrapper and should not affect the quantum simulator itself since they are related to how certain time intervals were measured.
A quick fix is to exclude such file "util/tests/omp_integral_base.cpp" from the building process by commenting the corresponding lines in "/util/tests/makefile".

**Comment by charliegray** [comment]
Thanks for taking the time to address my issue.

I had already figured out the –qopenmp/-openmp flag.  I made the makefile modification you provided but the compile still aborts for highperfkernels.cpp and errors out.

Below is the documented build attempt.  Any suggestions would be welcome.

Regards,
Charles Gray
Senior Systems Administrator
Tufts Technology Services (TTS)
169 Holland Street
Somerville, MA 02144
(617) 627-5327 (w)
(617) 627-3307 (f)
it.tufts.edu

[root@omega025 ~]# module load intel/2013_sp1
[root@omega025 ~]# source /opt/intel/bin/compilervars.sh intel64
[root@omega025 ~]# env | grep PATH
MANPATH=/opt/intel/compilers_and_libraries_2018.2.199/linux/mpi/man:/usr/share/man:/opt/shared/intel/2013_sp1/man
LIBRARY_PATH=/opt/intel/compilers_and_libraries_2018.2.199/linux/tbb/lib/intel64_lin/gcc4.4:/opt/intel/compilers_and_libraries_2018.2.199/linux/compiler/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64_lin
LD_LIBRARY_PATH=/opt/intel/compilers_and_libraries_2018.2.199/linux/compiler/lib/intel64:/opt/intel/compilers_and_libraries_2018.2.199/linux/compiler/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.2.199/linux/mpi/intel64/lib:/opt/intel/compilers_and_libraries_2018.2.199/linux/mpi/mic/lib:/opt/intel/compilers_and_libraries_2018.2.199/linux/tbb/lib/intel64_lin/gcc4.4:/opt/intel/compilers_and_libraries_2018.2.199/linux/compiler/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64_lin:/opt/shared/intel/2013_sp1/composer_xe_2013_sp1.4.211/compiler/lib/intel64:/opt/shared/intel/2013_sp1/composer_xe_2013_sp1.4.211/mkl/lib/intel64/:/opt/shared/intel/2013_sp1/lib
CPATH=/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/include
NLSPATH=/opt/intel/compilers_and_libraries_2018.2.199/linux/compiler/lib/intel64/locale/%l_%t/%N:/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64_lin/locale/%l_%t/%N
PATH=/opt/intel/compilers_and_libraries_2018.2.199/linux/bin/intel64:/opt/intel/compilers_and_libraries_2018.2.199/linux/mpi/intel64/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/lpp/mmfs/bin:/root/bin:/opt/shared/intel/2013_sp1/bin
MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles:/opt/shared/Modules/modulefiles-rhel6
CLASSPATH=/opt/intel/compilers_and_libraries_2018.2.199/linux/mpi/intel64/lib/mpi.jar
PKG_CONFIG_PATH=/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/bin/pkgconfig
[root@omega025 ~]# icpc -v
icpc version 14.0.4 (gcc version 4.4.7 compatibility)
[root@omega025 ~]# mpiicc -v
mpiicc for the Intel(R) MPI Library 2018 Update 2 for Linux*
Copyright(C) 2003-2018, Intel Corporation.  All rights reserved.
icc version 14.0.4 (gcc version 4.4.7 compatibility)
[root@omega025 ~]# cd /opt/shared/qHiPSTER/src/Intel-QS-master
[root@omega025 Intel-QS-master]# make all
cd util; make
make[1]: Entering directory `/opt/shared/qHiPSTER/src/Intel-QS-master/util'
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64 -Wall -std=c++11 -openmp   -I./ -I../ -c mpi_wrapper.cpp -o mpi_wrapper.o
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64 -Wall -std=c++11 -openmp   -I./ -I../ -c mpi_exception.cpp -o mpi_exception.o
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64 -Wall -std=c++11 -openmp   -I./ -I../ -c mpi.cpp -o mpi.o
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64 -Wall -std=c++11 -openmp   -I./ -I../ -c utils.cpp -o utils.o
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64 -Wall -std=c++11 -openmp   -I./ -I../ -c openmp_affinity_noomp.cpp -o openmp_affinity_noomp.o
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64 -Wall -std=c++11 -openmp   -I./ -I../ -c openmp_affinity_corei7.cpp -o openmp_affinity_corei7.o
make[1]: Leaving directory `/opt/shared/qHiPSTER/src/Intel-QS-master/util'
cd util/tests; make
make[1]: Entering directory `/opt/shared/qHiPSTER/src/Intel-QS-master/util/tests'
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64 -Wall -std=c++11 -openmp   -I./ -I../ -c mpi_exception_test.cpp -o mpi_exception_test.o
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64 -Wall -std=c++11 -openmp   -L/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64 -lmkl_cdft_core -lmkl_intel_ilp64 -lmkl_core -lmkl_intel_thread -lmkl_blacs_intelmpi_ilp64 -lpthread -lirc mpi_exception_test.o ../mpi_exception.o ../mpi_wrapper.o -o mpi_exception_test.exe
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64 -Wall -std=c++11 -openmp   -I./ -I../ -c mpi_test1.cpp -o mpi_test1.o
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64 -Wall -std=c++11 -openmp   -L/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64 -lmkl_cdft_core -lmkl_intel_ilp64 -lmkl_core -lmkl_intel_thread -lmkl_blacs_intelmpi_ilp64 -lpthread -lirc mpi_test1.o ../mpi_wrapper.o ../mpi_exception.o -o mpi_test1.exe
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64 -Wall -std=c++11 -openmp   -I./ -I../ -c omp_test1.cpp -o omp_test1.o
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64 -Wall -std=c++11 -openmp   -L/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64 -lmkl_cdft_core -lmkl_intel_ilp64 -lmkl_core -lmkl_intel_thread -lmkl_blacs_intelmpi_ilp64 -lpthread -lirc omp_test1.o ../openmp_affinity_corei7.o ../openmp_affinity_noomp.o -o omp_test1.exe
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64 -Wall -std=c++11 -openmp   -I./ -I../ -c naive_integral_base.cpp -o naive_integral_base.o
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64 -Wall -std=c++11 -openmp   -L/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64 -lmkl_cdft_core -lmkl_intel_ilp64 -lmkl_core -lmkl_intel_thread -lmkl_blacs_intelmpi_ilp64 -lpthread -lirc naive_integral_base.o -o naive_integral_base.exe
make[1]: Leaving directory `/opt/shared/qHiPSTER/src/Intel-QS-master/util/tests'
cd qureg; make
make[1]: Entering directory `/opt/shared/qHiPSTER/src/Intel-QS-master/qureg'
mpiicpc -g -O3 -DUSE_MM_MALLOC -DSTANDALONE -DOPENQU_HAVE_MPI -DMKL_ILP64 -Wall -std=c++11 -openmp   -I./ -I../ -c highperfkernels.cpp -o highperfkernels.o
In file included from qureg.hpp(26),
                 from highperfkernels.hpp(18),
                 from highperfkernels.cpp(17):
../util/tinymatrix.hpp(43): error: identifier "alignof" is undefined
  template <class ValueType, unsigned M, unsigned N = M, unsigned align = alignof(ValueType)>
                                                                          ^

In file included from qureg.hpp(26),
                 from highperfkernels.hpp(18),
                 from highperfkernels.cpp(17):
../util/tinymatrix.hpp(43): error: type name is not allowed
  template <class ValueType, unsigned M, unsigned N = M, unsigned align = alignof(ValueType)>
                                                                                  ^

In file included from qureg.hpp(26),
                 from highperfkernels.hpp(18),
                 from highperfkernels.cpp(17):
../util/tinymatrix.hpp(273): error: constant "align" is not a type name
    alignas(align == 0 ? 8 : align) ValueType data_[M][N];
            ^

In file included from qureg.hpp(26),
                 from highperfkernels.hpp(18),
                 from highperfkernels.cpp(17):
../util/tinymatrix.hpp(273): error: expected a ")"
    alignas(align == 0 ? 8 : align) ValueType data_[M][N];
                  ^

In file included from qureg.hpp(26),
                 from highperfkernels.hpp(18),
                 from highperfkernels.cpp(17):
../util/tinymatrix.hpp(273): error #303: explicit type is missing ("int" assumed)
    alignas(align == 0 ? 8 : align) ValueType data_[M][N];
    ^

In file included from qureg.hpp(26),
                 from highperfkernels.hpp(18),
                 from highperfkernels.cpp(17):
../util/tinymatrix.hpp(273): error: expected a ";"
    alignas(align == 0 ? 8 : align) ValueType data_[M][N];
                           ^

In file included from qureg.hpp(247),
                 from highperfkernels.hpp(18),
                 from highperfkernels.cpp(17):
NoisyQureg.hpp(52): error: namespace "std" has no member "default_random_engine"
      std::default_random_engine generator;
           ^

TODO - Not using ICC vectorization since it sucks: need to rewrite in intrincics
../util/tinymatrix.hpp(206): error: identifier "data_" is undefined
      return data_[i];
             ^
          detected during instantiation of "void Loop_SN(size_t={unsigned long}, size_t={unsigned long}, Type *, Type *, size_t={unsigned long}, size_t={unsigned long}, const TM2x2<Type> &, bool, Timer *) [with Type=ComplexSP]" at line 252 of "highperfkernels.cpp"

TODO - Allow for case where state is not aligned: need SIMD ISA for un-aligned access
TODO - Add nthreads check to clamp to smaller number of too little work
TODO - Generalize for AVX3 cases so we check for pos <=1 etc
TODO - Generalize for AVX3 cases so we check for pos <=1 etc
TODO - Allow for case where state is not aligned: need SIMD ISA for un-aligned access
TODO - Add nthreads check to clamp to smaller number of too little work
TODO - Generalize for AVX3 cases so we check for pos <=1 etc
TODO - Generalize for AVX3 cases so we check for pos <=1 etc
TODO - Allow for case where state is not aligned: need SIMD ISA for un-aligned access
TODO - Add nthreads check to clamp to smaller number of too little work
TODO - Generalize for AVX3 cases so we check for pos <=1 etc
TODO - Generalize for AVX3 cases so we check for pos <=1 etc
compilation aborted for highperfkernels.cpp (code 2)
make[1]: *** [highperfkernels.o] Error 2
make[1]: Leaving directory `/opt/shared/qHiPSTER/src/Intel-QS-master/qureg'
make: *** [all] Error 2
[root@omega025 Intel-QS-master]#

**Comment by jwhogabo** [comment]
Most recent CMake build system will automatically apply the correct openmp flag to the compiler.
