### ISSUE TITLE
I cannot push a feature branch to create a merge request

### ISSUE THREAD

**Issue by mbuchberger1967** [intel/intel-qs#53]
Hi,
I cloned the repo to my machine, created a branch to support  #52 but I am not allowed to push my branch. 
What did I wrong?

BR

**Comment by giangiac** [comment]
Hi BR,

Are you pushing to "master" or "development"?
Master is a protected branch and the recommended flow is opening a pull-request into branch development:
https://github.com/iqusoft/intel-qs/blob/master/CONTRIBUTING.md

G

**Comment by mbuchberger1967** [comment]
Hi,
thx for the answer.
I cannot push my branch which contains the feature...
I created the branch local and wanted to push it to your repo.... as a prerequisite of a pull-request, right?
BR

**Comment by mbuchberger1967** [comment]
Hi @giangiac 
I am not pushing neither to master nor to development.
As I understand your contribution rules, I created a feature branch for it, and I wanted to push this branch. But I cannot, I'm not allowed to push a branch. Do I miss something here?

**Comment by giangiac** [comment]
In principle you should be able to create a new branch, push to it, and create a merge request to development.

I understand that you created the branch locally and cannot push it to the remote. I am not sure why not.
Have you tried to create the branch directly in github and then track it from you local branch?

**Comment by mbuchberger1967** [comment]
yes I wanted to do this.
But I cannot find any possibility to create a new branch in the github web UI.
Is it possible that I need to fork your repo, push it to my repo and create a pull-request from there?

**Comment by giangiac** [comment]
We had new branches from other users without the need to fork.

To create a new branch, from https://github.com/iqusoft/intel-qs click on "master" and you should see the "find or create a new branch" option.

**Comment by mbuchberger1967** [comment]
Nope, unfortunately not....
![grafik](https://user-images.githubusercontent.com/25125667/126669138-01619b5f-cde2-46b7-88da-b365bd6b146b.png)

**Comment by giangiac** [comment]
Anything like this?
![image](https://user-images.githubusercontent.com/30329377/126739964-42f19e63-bdec-4434-b429-fa6b5f66a152.png)

**Comment by mbuchberger1967** [comment]
No, strange
![image](https://user-images.githubusercontent.com/25125667/126750264-85b3d19e-67b4-475e-b103-b712f10c76f6.png)

**Comment by mbuchberger1967** [comment]
I could only create a branch and pull request by forking the repo.
I couldn't work contribute directly to your repo.

**Comment by giangiac** [comment]
Interesting behavior, not sure why this happens.
I see you managed to create pull requests, I'll give a look at them to verify that at least the forking does all the job.

**Comment by mbuchberger1967** [comment]
we do pull requests via a fork, taht works. We cannot create pull requests directly.
