### ISSUE TITLE
new Environment() always prints out messages in terminal window

### ISSUE THREAD

**Issue by mbuchberger1967** [intel/intel-qs#58]
**Is your feature request related to a problem? Please describe.**
It is not possible to do an silent init of intel-qs lib

**Describe the solution you'd like**
A flag 'silent' in the ctor to control if outputs are done to the terminal

**Additional context**
I did an impl for this in PR #59

**Comment by giangiac** [comment]
Hi @mbuchberger1967,

the effect of flag 'silent' is the same of argument variable 'do_print_info' in method
iqs::mpi::Environment::UpdateStateComm().

I believe this should be consolidated and will propose edits to the PR.

**Comment by mbuchberger1967** [comment]
this is correct. I did a parallel implementation as I didnt want to break any existing logic.
I'm happy if you consolidate the two flags into one.

**Comment by mbuchberger1967** [comment]
I saw you updated my PR and I think this can be closed now.
