### ISSUE TITLE
Sudden compilation fail due to libeigen/eigen

### ISSUE THREAD

**Issue by flyree** [intel/Intel-QS#66]
**Describe the bug**
I tried to compile an example in the tutorial. Upon last night things work fine. I tried just now and it seems that the compilation does not work anymore. The reason I believe is that the repo libeigen/eigen does not exist anymore and the Cmake wants to get updates from that library. 

**To Reproduce**
1. Go to build/tutorials
2. make

**Screenshots**
[  2%] Performing update step for 'deps-eigen'
remote: A repository for this project does not exist yet.
fatal: repository 'https://gitlab.com/libeigen/eigen.git/' not found
CMake Error at /scratch1/08177/bfpnnl/intel-qs-new/intel-qs/build/deps/eigen-prefix/tmp/deps-eigen-gitupdate.cmake:55 (message):
  Failed to fetch repository 'https://gitlab.com/libeigen/eigen.git'

make[2]: *** [deps/eigen-prefix/src/deps-eigen-stamp/deps-eigen-update] Error 1
make[1]: *** [src/CMakeFiles/deps-eigen.dir/all] Error 2
make: *** [all] Error 2

I see this library should already exist on my local. Can I skip this step and just use my local version?

**Comment by giangiac** [comment]
Hi @flyree ,
it is a problem with Eigen. See message "NOTICE! We are troubleshooting a technical problem. The main Eigen repository on GitLab is currently offline." in their home page:
https://eigen.tuxfamily.org/index.php?title=Main_Page

Eigen is used only for simulations with noise but the current build requires it by default.
I think the Eigen team will solve the issue quickly, but a way to move forward would be adding a build option that enable/disable the noisy simulation.

**Comment by flyree** [comment]
I see. Thank you for the response. Hopefully, this would be resolved by them soon!

**Comment by giangiac** [comment]
It seems that repository Eigen is back online.
However this gave me the motivation to include it in the building process as optional (instead of as a requirement).
See pull-request #67 .
